package com.staffs.leavebooking.leavemanagement.infrastructure.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDate;

/**
 * JPA entity mapping to the {@code leave_request} database table
 * (Lecture 3 — Infrastructure Layer, Persistence).
 *
 * <p><strong>Separation from domain:</strong> This JPA entity is kept separate from
 * the domain aggregate ({@link com.staffs.leavebooking.leavemanagement.domain.LeaveRequest}).
 * The domain aggregate has no JPA annotations — it's pure business logic.
 * Mappers convert between the two representations:
 * <ul>
 *   <li>{@link com.staffs.leavebooking.leavemanagement.application.mappers.LeaveRequestDomainToJpaMapper} — domain → JPA (for writes)</li>
 *   <li>{@link com.staffs.leavebooking.leavemanagement.application.mappers.LeaveRequestJpaToDomainMapper} — JPA → domain (for command loading)</li>
 *   <li>{@link com.staffs.leavebooking.leavemanagement.application.mappers.LeaveRequestJpaToDTOMapper} — JPA → DTO (for queries, bypassing domain)</li>
 * </ul>
 *
 * <p><strong>14 columns:</strong> The table stores the full lifecycle of a leave request,
 * including submission data (staffMemberId, managerId, dates, type, reason), status tracking
 * (status, submittedOn), decision data (decidedOn, decidedBy, decisionReason), and
 * cancellation data (cancellationReason). Nullable columns (decidedOn, decidedBy,
 * decisionReason, cancellationReason) are only populated after the corresponding action.
 *
 * <p><strong>ID strategy:</strong> The ID is a UUID String (not auto-generated) because
 * it's generated by the domain layer using {@link com.staffs.leavebooking.common.domain.Identity#generateId()}.
 * This follows DDD practice: the domain controls identity generation, not the database.
 *
 * <p><strong>Jakarta Validation annotations:</strong> {@code @NotBlank}, {@code @NotNull},
 * {@code @Positive}, {@code @Size} provide database-level validation as a safety net.
 * The primary validation happens in the domain layer (DomainAssertions), but these
 * annotations catch any data that bypasses the domain (e.g., direct SQL inserts, test data).
 *
 * <p><strong>Lombok annotations:</strong>
 * <ul>
 *   <li>{@code @Getter} — generates getters for all fields (used by mappers and serialisation)</li>
 *   <li>{@code @Setter} — generates setters for all fields (required by JPA for entity hydration)</li>
 *   <li>{@code @ToString} — generates toString() for logging/debugging</li>
 * </ul>
 *
 * @see com.staffs.leavebooking.leavemanagement.application.mappers.LeaveRequestDomainToJpaMapper for domain → JPA conversion
 * @see com.staffs.leavebooking.leavemanagement.application.mappers.LeaveRequestJpaToDomainMapper for JPA → domain conversion
 * @see com.staffs.leavebooking.leavemanagement.application.mappers.LeaveRequestJpaToDTOMapper for JPA → DTO conversion (read path)
 */
@Entity(name = "leave_request")  // JPA entity name — used in JPQL queries
@Table(name = "leave_request")   // Maps to the leave_request table in the database
@Getter     // Lombok: generates getter methods for all fields
@Setter     // Lombok: generates setter methods for all fields (JPA requires setters for hydration)
@ToString   // Lombok: generates toString() for logging
public class LeaveRequestJpa {

    /**
     * Primary key — a UUID generated by the domain layer.
     * Not auto-generated by the database; the domain controls identity via
     * {@link com.staffs.leavebooking.common.domain.Identity#generateId()}.
     */
    @Id // JPA primary key
    @Column(name = "id", length = 36) // UUID format: 36 chars with hyphens
    private String id;

    /** UUID of the staff member who submitted this leave request (= Firebase UID, required). */
    @NotBlank(message = "Staff member ID is required")  // Safety-net validation
    @Column(name = "staff_member_id", nullable = false, length = 36)
    private String staffMemberId;

    /** UUID of the manager assigned to approve/reject this request (required). */
    @NotBlank(message = "Manager ID is required")       // Safety-net validation
    @Column(name = "manager_id", nullable = false, length = 36)
    private String managerId;

    /**
     * Leave type stored as string (e.g., "ANNUAL").
     * Stored as string rather than {@code @Enumerated} to decouple the database schema
     * from the Java {@link com.staffs.leavebooking.leavemanagement.domain.LeaveType} enum.
     */
    @NotBlank(message = "Leave type is required")       // Safety-net validation
    @Column(name = "leave_type", nullable = false, length = 20)
    private String leaveType;

    /** First day of the leave period (required, validated in domain as today or future at submission). */
    @NotNull(message = "Start date is required")        // Safety-net validation
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** Last day of the leave period (required, validated in domain as >= startDate). */
    @NotNull(message = "End date is required")          // Safety-net validation
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /**
     * Calculated number of leave days between startDate and endDate (inclusive).
     * Calculated by the domain's {@link com.staffs.leavebooking.leavemanagement.domain.DateRange}
     * value object at submission time and stored for efficient querying.
     */
    @Positive(message = "Number of days must be positive") // Safety-net: must be at least 1
    @Column(name = "number_of_days", nullable = false)
    private int numberOfDays;

    /** Optional reason provided when the request was submitted (nullable, max 500 chars). */
    @Size(max = 500, message = "Reason must not exceed 500 characters")
    @Column(name = "reason", length = 500)
    private String reason;

    /**
     * Current lifecycle status stored as string (PENDING, APPROVED, REJECTED, CANCELLED).
     * Stored as string rather than {@code @Enumerated} for schema flexibility.
     * Status transitions are enforced by the domain aggregate, not the database.
     */
    @NotBlank(message = "Status is required")           // Safety-net validation
    @Column(name = "status", nullable = false, length = 20)
    private String status;

    /** Date the leave request was submitted — set automatically by the domain at creation time. */
    @NotNull(message = "Submitted on date is required") // Safety-net validation
    @Column(name = "submitted_on", nullable = false)
    private LocalDate submittedOn;

    /** Date the request was approved or rejected — null while PENDING, set by the domain on decision. */
    @Column(name = "decided_on")
    private LocalDate decidedOn;

    /** UUID of the manager/admin who approved or rejected — null while PENDING. */
    @Column(name = "decided_by", length = 36)
    private String decidedBy;

    /** Optional reason given when approving/rejecting the request — nullable (manager may not provide one). */
    @Size(max = 500, message = "Decision reason must not exceed 500 characters")
    @Column(name = "decision_reason", length = 500)
    private String decisionReason;

    /** Optional reason given when cancelling the request — nullable (only set on CANCELLED status). */
    @Size(max = 500, message = "Cancellation reason must not exceed 500 characters")
    @Column(name = "cancellation_reason", length = 500)
    private String cancellationReason;
}
