package com.staffs.leavebooking.leavemanagement.infrastructure.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * JPA entity mapping to the {@code leave_allowance} database table
 * (Lecture 3 — Infrastructure Layer, Persistence).
 *
 * <p><strong>Purpose:</strong> Holds the annual leave balance for a staff member in a
 * given business year. Tracks the total entitlement, days used (from APPROVED requests),
 * and days pending (from PENDING requests). The difference between these values gives
 * the remaining and available days, which are calculated at DTO mapping time.
 *
 * <p><strong>Separation from domain:</strong> This JPA entity is kept separate from
 * the domain aggregate ({@link com.staffs.leavebooking.leavemanagement.domain.LeaveAllowance}).
 * The domain aggregate has no JPA annotations — it's pure business logic.
 * Mappers convert between the two representations:
 * <ul>
 *   <li>{@link com.staffs.leavebooking.leavemanagement.application.mappers.LeaveAllowanceDomainToJpaMapper} — domain → JPA (for writes)</li>
 *   <li>{@link com.staffs.leavebooking.leavemanagement.application.mappers.LeaveAllowanceJpaToDomainMapper} — JPA → domain (for command loading)</li>
 *   <li>{@link com.staffs.leavebooking.leavemanagement.application.mappers.LeaveAllowanceJpaToDTOMapper} — JPA → DTO (for queries, bypassing domain)</li>
 * </ul>
 *
 * <p><strong>Denormalised staff details:</strong> The {@code firstName}, {@code surname},
 * {@code managerId}, and {@code department} fields are snapshots of data from the Staff
 * Management bounded context. They are synced via RabbitMQ events
 * ({@code StaffMemberAddedEvent}, {@code StaffMemberUpdatedEvent}) to avoid cross-context
 * queries when displaying allowance data. This is a deliberate denormalisation trade-off:
 * slightly stale data is acceptable in exchange for context isolation.
 *
 * <p><strong>Unique constraint:</strong> The combination of {@code staff_member_id} and
 * {@code business_year_start} is unique, ensuring that each staff member has at most one
 * allowance per business year. This is enforced at the database level via
 * {@code @UniqueConstraint} and at the application level via the idempotency guard in
 * {@link com.staffs.leavebooking.leavemanagement.application.handlers.LeaveAllowanceApplicationService#createAllowanceForNewStaff}.
 *
 * <p><strong>ID strategy:</strong> The ID is a UUID String (not auto-generated) because
 * it's generated by the domain layer using {@link com.staffs.leavebooking.common.domain.Identity#generateId()}.
 *
 * <p><strong>Lombok annotations:</strong>
 * <ul>
 *   <li>{@code @Getter} — generates getters for all fields (used by mappers and serialisation)</li>
 *   <li>{@code @Setter} — generates setters for all fields (required by JPA for entity hydration)</li>
 *   <li>{@code @ToString} — generates toString() for logging/debugging</li>
 * </ul>
 *
 * @see com.staffs.leavebooking.leavemanagement.application.mappers.LeaveAllowanceDomainToJpaMapper for domain → JPA conversion
 * @see com.staffs.leavebooking.leavemanagement.application.mappers.LeaveAllowanceJpaToDomainMapper for JPA → domain conversion
 * @see com.staffs.leavebooking.leavemanagement.application.mappers.LeaveAllowanceJpaToDTOMapper for JPA → DTO conversion (read path)
 */
@Entity(name = "leave_allowance")    // JPA entity name — used in JPQL queries
@Table(name = "leave_allowance",     // Maps to the leave_allowance table in the database
        uniqueConstraints = @UniqueConstraint(
                name = "uq_allowance_staff_year",                      // Named constraint for clarity in error messages
                columnNames = {"staff_member_id", "business_year_start"} // One allowance per staff member per year
        ))
@Getter     // Lombok: generates getter methods for all fields
@Setter     // Lombok: generates setter methods for all fields (JPA requires setters for hydration)
@ToString   // Lombok: generates toString() for logging
public class LeaveAllowanceJpa {

    /**
     * Primary key — a UUID generated by the domain layer.
     * Not auto-generated by the database; the domain controls identity via
     * {@link com.staffs.leavebooking.common.domain.Identity#generateId()}.
     */
    @Id // JPA primary key
    @Column(name = "id", length = 36) // UUID format: 36 chars with hyphens
    private String id;

    /** UUID of the staff member this allowance belongs to (= Firebase UID, required). */
    @NotBlank(message = "Staff member ID is required")  // Safety-net validation
    @Column(name = "staff_member_id", nullable = false, length = 36)
    private String staffMemberId;

    /**
     * UUID of the staff member's line manager (denormalised from Staff Management).
     * Synced via RabbitMQ events when the staff member's manager changes.
     */
    @NotBlank(message = "Manager ID is required")       // Safety-net validation
    @Column(name = "manager_id", nullable = false, length = 36)
    private String managerId;

    /**
     * Staff member's first name (denormalised from Staff Management).
     * Stored here to avoid cross-context queries when displaying allowance data.
     */
    @NotBlank(message = "First name is required")       // Safety-net validation
    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;

    /**
     * Staff member's surname (denormalised from Staff Management).
     * Combined with firstName to form the staffName in the DTO.
     */
    @NotBlank(message = "Surname is required")          // Safety-net validation
    @Column(name = "surname", nullable = false, length = 50)
    private String surname;

    /**
     * Staff member's department (denormalised from Staff Management).
     * Synced via RabbitMQ events when the staff member's department changes.
     * Used for the "filter by department" query on the admin view.
     */
    @Column(name = "department", length = 100)          // Nullable — may not be set yet
    private String department;

    /**
     * Start year of the business year this allowance covers (e.g., 2025 for 2025/2026).
     * Part of the unique constraint with staffMemberId — one allowance per year.
     */
    @NotNull(message = "Business year start is required")   // Safety-net validation
    @Column(name = "business_year_start", nullable = false)
    private Integer businessYearStart;

    /**
     * End year of the business year this allowance covers (e.g., 2026 for 2025/2026).
     * Stored for display purposes — the DTO formats this as "2025/2026".
     */
    @NotNull(message = "Business year end is required")     // Safety-net validation
    @Column(name = "business_year_end", nullable = false)
    private Integer businessYearEnd;

    /**
     * Total annual leave entitlement in days (e.g., 25 days).
     * Set when the allowance is created (from the organisation's default) and
     * can be amended by an admin via PATCH /leave-allowances/{id}.
     */
    @Positive(message = "Total entitlement must be positive") // Must be at least 1 day
    @Column(name = "total_entitlement", nullable = false)
    private int totalEntitlement;

    /**
     * Number of leave days already used (from APPROVED requests).
     * Incremented when a request is approved; decremented when an approved request is cancelled.
     */
    @PositiveOrZero(message = "Days used cannot be negative") // 0 or more
    @Column(name = "days_used", nullable = false)
    private int daysUsed;

    /**
     * Number of leave days currently reserved by PENDING requests.
     * Incremented when a request is submitted; decremented when a pending request is
     * approved (moved to daysUsed), rejected, or cancelled.
     */
    @PositiveOrZero(message = "Days pending cannot be negative") // 0 or more
    @Column(name = "days_pending", nullable = false)
    private int daysPending;
}
